### ISSUE TITLE
Fix RoverGarbageCollector for following issues:

### ISSUE THREAD

**Issue by mo3pheus** [mo3pheus/MarsRover#2]
1) Should not get comsDelay when processing instructionQueue
2) Should have error recovery in case of exceptions while processingInstructionQueue.

**Comment by mo3pheus** [comment]
@mo3pheus testing email notifications.

**Comment by mo3pheus** [comment]
Fixed errorRecovery for RoverGarbageCollector.

2017-12-16 21:25:49,666 [pool-33-thread-1] INFO space.exploration.mars.rover.diagnostics.RoverGarbageCollector  - RoverGC trimming instructionQueue. Current length = 8
2017-12-16 21:25:49,666 [pool-29-thread-1] INFO space.exploration.mars.rover.power.BatteryMonitor  - BatteryMonitor performing due diligence. SCET = 1513481149666 Rover state = Listening State
2017-12-16 21:25:49,666 [pool-33-thread-1] INFO space.exploration.mars.rover.kernel.ListeningState  - timeStamp: 1513480912313
targets {
  roverModule: 5
  estimatedPowerUsage: 30
  action: "Explore"
}

2017-12-16 21:25:55,686 [pool-33-thread-1] INFO space.exploration.mars.rover.kernel.ListeningState  - 1513481155686,5,Explore Current instructionQueue length = 7
2017-12-16 21:25:55,686 [pool-33-thread-1] INFO space.exploration.mars.rover.kernel.ListeningState  - Rover Curiosity is on a scientific mission!
2017-12-16 21:26:26,795 [pool-33-thread-1] ERROR space.exploration.mars.rover.diagnostics.RoverGarbageCollector  - Encountered exception while processing instructionQueue
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at space.exploration.spice.utilities.PositionUtils.getPositionPacket(PositionUtils.java:37)
	at space.exploration.mars.rover.kernel.PositionSensor.getPositionsData(PositionSensor.java:65)
	at space.exploration.mars.rover.communication.Radio.getComsDelaySecs(Radio.java:122)
	at space.exploration.mars.rover.communication.Radio.sendMessage(Radio.java:77)
	at space.exploration.mars.rover.kernel.TransmittingState.transmitMessage(TransmittingState.java:43)
	at space.exploration.mars.rover.kernel.Rover.transmitMessage(Rover.java:335)
	at space.exploration.mars.rover.kernel.ExploringState.exploreArea(ExploringState.java:66)
	at space.exploration.mars.rover.kernel.Rover.exploreArea(Rover.java:331)
	at space.exploration.mars.rover.kernel.ListeningState.receiveMessage(ListeningState.java:93)
	at space.exploration.mars.rover.kernel.Rover.receiveMessage(Rover.java:303)
	at space.exploration.mars.rover.kernel.Rover.processPendingMessageQueue(Rover.java:128)
	at space.exploration.mars.rover.diagnostics.RoverGarbageCollector$QueueMonitor.run(RoverGarbageCollector.java:64)
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-16 21:26:26,796 [pool-33-thread-1] INFO space.exploration.mars.rover.diagnostics.RoverGarbageCollector  - RoverGC trimming instructionQueue. Current length = 7
2017-12-16 21:26:26,795 [pool-29-thread-1] INFO space.exploration.mars.rover.power.BatteryMonitor  - BatteryMonitor performing due diligence. SCET = 1513481186795 Rover state = Transmitting State
2017-12-16 21:26:26,796 [pool-33-thread-1] INFO space.exploration.mars.rover.kernel.ListeningState  - timeStamp: 1513480915749

**Comment by mo3pheus** [comment]
RoverGarbageCollector does not encounter a coms delay when processing InstructionQueue. Point #1 is invalid. Rover is working as designed.

**Comment by mo3pheus** [comment]
This has been fixed so that the garbageCollector recovers even upon encountering errors while processing the instructionQueue.
